# line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '7.0'
target ‘AdvertisingPageTest’ do
    
pod 'AFNetworking','3.1.0'
pod 'SDWebImage', '~> 3.7.3'
end

target ‘AdvertisingPageTestTests' do

end
